const menuBtn=document.getElementById('menuBtn');const navLinks=document.getElementById('navLinks');const modal=document.getElementById('modal');const modalTitle=document.getElementById('modalTitle');const modalDesc=document.getElementById('modalDesc');const modalList=document.getElementById('modalList');const modalKicker=document.getElementById('modalKicker');
menuBtn.addEventListener('click',()=>navLinks.classList.toggle('open'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));document.getElementById('year').textContent=new Date().getFullYear());
const people=[
{id:1,name:'Nguyễn Văn An',unit:'Giáo xứ Hải Ninh',role:'Giáo dân',family:'Hộ gia đình Nguyễn Văn',phone:'Chưa cập nhật',address:'Hải Ninh',groups:'Cộng đoàn giáo xứ'},
{id:2,name:'Trần Thị Bình',unit:'Giáo xứ Hải Ninh',role:'Giáo dân',family:'Hộ gia đình Trần Thị',phone:'Chưa cập nhật',address:'Hải Ninh',groups:'Hội Con Đức Mẹ'},
{id:3,name:'Lê Văn Cường',unit:'Giáo họ Viên Chử',role:'Giáo dân',family:'Hộ gia đình Lê Văn',phone:'Chưa cập nhật',address:'Viên Chử',groups:'Giới trẻ'},
{id:4,name:'Phạm Thị Dung',unit:'Giáo họ Viên Chử',role:'Giáo dân',family:'Hộ gia đình Phạm Thị',phone:'Chưa cập nhật',address:'Viên Chử',groups:'Tràng Hạt Mân Côi'}
];
function renderPeople(){const q=document.getElementById('peopleSearch').value.toLowerCase().trim();const unit=document.getElementById('unitFilter').value;const list=people.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(unit==='all'||p.unit===unit));document.getElementById('peopleList').innerHTML=list.length?list.map(p=>`<button class="person-row" data-person="${p.id}"><span class="avatar">${p.name.split(' ').map(x=>x[0]).slice(-2).join('')}</span><span class="person-main"><b>${p.name}</b><small>${p.unit} · ${p.family}</small></span><span class="person-arrow">Xem hồ sơ 360° →</span></button>`).join(''):'<div class="empty-state">Không tìm thấy giáo dân phù hợp.</div>';document.querySelectorAll('[data-person]').forEach(el=>el.addEventListener('click',()=>openProfile(Number(el.dataset.person))))}
function openProfile(id){const p=people.find(x=>x.id===id);if(!p)return;modalKicker.textContent='HỒ SƠ GIÁO DÂN 360°';modalTitle.textContent=p.name;modalDesc.textContent='Thông tin tổng hợp của giáo dân trong hệ thống Giáo xứ Hải Ninh.';modalList.innerHTML=`<div><small>Đơn vị</small><strong>${p.unit}</strong></div><div><small>Vai trò</small><strong>${p.role}</strong></div><div><small>Hộ gia đình</small><strong>${p.family}</strong></div><div><small>Địa chỉ</small><strong>${p.address}</strong></div><div><small>Điện thoại</small><strong>${p.phone}</strong></div><div><small>Sinh hoạt hội đoàn</small><strong>${p.groups}</strong></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.getElementById('peopleSearch').addEventListener('input',renderPeople);document.getElementById('unitFilter').addEventListener('change',renderPeople);renderPeople();
const modules={pastors:{kicker:'LỊCH SỬ MỤC VỤ',title:'Các vị Mục tử qua từng thời kỳ',desc:'Khu vực lưu trữ lịch sử phục vụ của các vị mục tử tại Giáo xứ Hải Ninh.',items:['Danh sách theo từng thời kỳ','Thông tin thời gian phục vụ','Ảnh và tiểu sử khi được bổ sung','Ghi chú lịch sử mục vụ']}};
function openModule(key){const data=modules[key];if(!data)return;modalKicker.textContent=data.kicker;modalTitle.textContent=data.title;modalDesc.textContent=data.desc;modalList.innerHTML=data.items.map(x=>`<div><strong>${x}</strong></div>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden')}
const today=new Date();document.getElementById('todayLabel').textContent=today.toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});document.querySelectorAll('.org-item').forEach(el=>el.addEventListener('click',()=>showNotice(`Mục “${el.textContent.replace('→','').trim()}” đang được chuẩn bị.`)));function showNotice(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}